#!/bin/bash
# the echos were just for fast debugging, now they're commented out

# check if the script is already running
running=`ps -A | grep break | wc -l`
if [ $running -gt 2 ]
then 
    exit
fi

# get a random number
number=$RANDOM
# modulo 80
let "number %= 80"
# set an increment. Walk is increased every time we decline walking 
let walk=1
while [ $walk -gt 0 ]
do
    # echo "sleeping ${number} minutes"
    sleep ${number}m
    zenity --question --text="You should take a 5 minute break, walk around a bit. Want to do this now?" --cancel-label=Later --ok-label=Now
    # reads in the response to the zenity question
    case $? in
        0)
            # echo "Now."
            walk=-1
            ;;
        1)
            # echo "Later."
            let "walk=$walk+1"
            ;;
        -1)
            # should never trigger, there are only 2 buttons on the zenity
            notify-send "An unexpected error has occurred."
            ;;
    esac
    # define new random number, set to modulo 80, then divide by number of times refused
    number=$RANDOM
    # echo $number
    let "number %= 80"
    # echo $number
    number=`echo "$number / $walk" | bc`
    # echo $number
done
